import "./globals.css";
import classnames from "classnames";
import { Fira_Code } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fira_code = Fira_Code({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={classnames(
          "bg-slate-950 font-inter text-slate-400",
          fira_code.className
        )}
      >
        {children}
      </body>
    </html>
  );
}
