// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Users struct {
	ID          uuid.UUID
	Email       string
	FirstName   pgtype.Text
	LastName    pgtype.Text
	DateOfBirth pgtype.Date
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
